minimal_mistakes_skin: default
locale: ko-KR
title: 테스트중
title_separator: '&#124;'
# subtitle: version 1.0
name: Sun-A Du
description: 안녕세상!
url: 'https://dusunax.github.io/'
repository: dusunax/dusunax.github.com
teaser: true
logo: assets/img/profile/unicon.png
masthead_title: 개발 블로그 겸 포트폴리오
breadcrumbs: true
words_per_minute: 200

author:
  name: Sun-A Du
  avatar: assets/img/profile/202112.jpg
  bio: 공부하는 사람
  location: Seoul, Republic of Korea
  links:
    - label: dusunax@gmail.com
      icon: fas fa-fw fa-envelope-square
      url: 'mailto:dusunax@gmail.com'
    - label: '@dusunax'
      icon: fab fa-fw fa-github
      url: 'https://github.com/dusunax'
footer:
  links:
    - label: ''
      icon: fas fa-fw fa-envelope-square
      url: 'mailto:dusunax@gmail.com'
    - label: ''
      icon: fab fa-fw fa-github
      url: 'https://github.com/dusunax'
include:
  - .htaccess
  - _pages
exclude:
  - '*.sublime-project'
  - '*.sublime-workspace'
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
  - /docs
  - /test
keep_files:
  - .git
  - .svn
encoding: utf-8
markdown_ext: 'markdown,mkdown,mkdn,mkd,md'
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: |+
comments:
  provider: 'disqus'
  disqus:
    shortname: 'fristGitblog'

incremental: false
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: 'lsquo,rsquo,ldquo,rdquo'
  enable_coderay: false
sass:
  sass_dir: _sass
  style: compressed
permalink: '/:categories/:title/'
paginate: 5
paginate_path: '/page:num/'
timezone: null
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
compress_html:
  clippings: all
  ignore:
    envs: development

defaults:
  - scope:
      path: ''
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: false
      related: false
  - scope:
      path: _pages
      type: pages
    values:
      layout: single
      author_profile: true
      share: false
      
